In [1]:
import matplotlib.pyplot as plt
plt.rc('font', size=12)
import pandas as pd
import seaborn as sns
import warnings 

import RuleQuality as RQ
import Coverage as cov

warnings.filterwarnings('ignore')
%matplotlib inline

%load_ext autoreload
%autoreload 2

## Params

In [2]:
#get list of client rules sorted by count
popSize = 10
clientFilename = "../Data/ICU/Best/"
# clientFilename = "../Data/ICU/Test/"
# clientFilename = "../Data/Sepsis/Best/"

# ldpFilename = "../Results/Sepsis_Base_TEST.csv"
# ldpFilename = "../Results/TEST/ICU_Base_TEST.csv"
# ldpFilename = "../Results/ICU_Ruleset_MCTS_TEST.csv"
ldpFilename = "../Results/Test/ICU_Base_TEST.csv"
# ldpFilename = "../Results/Sepsis_Ruleset_MCTS_Test.csv"

## Load Client Rules & Data

In [3]:
# Load Client Rule Trees and Text Rule Structures, and get dataframe of rules and their counts
clientTrees, clientRules, clientDF = cov.loadClientRules(popSize, clientFilename)
clientDF

File not found for Client 8

,Rule,Rule Count,Percent of Population
53,"((MET >= 0.000) U[0,0] (death = 0.000))",17,1.0
56,"F[0,0]((BLOOD_UREA_NITROGEN <= 0.000 & CREATIN...",13,1.0
57,"G[0,0]((n_evts <= 0.000 -> LOS >= 0.000))",12,1.0
47,"G[0,0]((hr >= 0.000 & Pulse >= 0.000))",3,0.3
172,"((af >= 0.000) U[0,0] (direct >= 0.000))",3,0.3
...,...,...,...
188,"F[0,0]((HEMOGLOBIN <= 0.000 & O2_Flow <= 0.000))",1,0.1
187,"F[0,0]((dfa >= 0.000 & Mort >= 0.000))",1,0.1
186,"((O2_Flow <= 0.000) U[0,0] (PLATELET_COUNT >= ...",1,0.1
185,"((MET >= 0.000) U[0,0] (PARTIAL_THROMBOPLASTIN...",1,0.1
552,"G[0,0]((death >= 0.000 -> WHITE_BLOOD_CELL_COU...",1,0.1

In [4]:
clientData, clientLabels = RQ.loadClientData(popSize)
clientData

File not found for Client 8

,LOS,ICU_Pt_Days,Mort,n_evts,y,tte,death,direct,MET,Sgy,...,edrk,s2_edrk,s8_edrk,s24_edrk,srr,dfa,cosen,lds,af,AF
1,4,1,0,0,False,0.0,0.0,0.0,0.0,0.0,...,23.527702,0.000002,0.000001,-4.918909e-07,0.027926,0.722903,-2.391665,1.670820,0.0,0.0
1,4,1,0,0,False,0.0,0.0,0.0,0.0,0.0,...,25.659513,0.002369,0.002369,2.368679e-03,0.031948,0.728738,-2.432732,1.995264,0.0,0.0
1,4,1,0,0,False,0.0,0.0,0.0,0.0,0.0,...,26.504228,0.001654,0.001654,1.653626e-03,0.023217,0.804216,-2.459413,2.058334,0.0,0.0
1,4,1,0,0,False,0.0,0.0,0.0,0.0,0.0,...,26.203203,0.000986,0.000986,9.856909e-04,0.010812,0.974394,-2.455503,1.986356,0.0,0.0
1,4,1,0,0,False,0.0,0.0,0.0,0.0,0.0,...,24.115443,0.000191,0.000191,1.910191e-04,0.007782,0.768893,-2.429776,1.900642,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5638,5,5,1,1,False,0.0,0.0,0.0,0.0,0.0,...,13.536963,0.000002,0.000001,-4.918909e-07,0.122448,0.914080,-2.126541,1.287429,0.0,0.0
5638,5,5,1,1,False,0.0,0.0,0.0,0.0,0.0,...,15.767800,0.002479,0.002479,2.478707e-03,0.136157,1.096900,-2.210947,1.536716,0.0,0.0
5638,5,5,1,1,False,0.0,0.0,0.0,0.0,0.0,...,20.571711,0.003908,0.003908,3.908193e-03,0.132757,0.934796,-2.238554,1.505370,0.0,0.0
5638,5,5,1,1,False,0.0,0.0,0.0,0.0,0.0,...,13.536963,0.000002,0.000001,-4.918909e-07,0.122448,0.914080,-2.126541,1.287429,0.0,0.0
5638,5,5,1,1,False,0.0,0.0,0.0,0.0,0.0,...,15.767800,0.002479,0.002479,2.478707e-03,0.136157,1.096900,-2.210947,1.536716,0.0,0.0

## Load LDP Rules

In [5]:
ldpDF, ldpTrees, ldpRules = cov.loadLDPRuleset(ldpFilename)
ldpDF

                                                  Rule  Percent Count
181      ((s24_hr > 0.000) U[0,0] (POTASSIUM < 0.000))            1.0
149  G[0,0]((BLOOD_UREA_NITROGEN = 0.000 | ICU_Pt_D...            1.0
139          ((death = 0.000) U[0,0] (n_edrk < 0.000))            1.0
527           F[0,0]((direct > 0.000 & death = 0.000))            1.0
526       ((MAGNESIUM > 0.000) U[0,0] (death > 0.000))            1.0
..                                                 ...            ...
233              G[0,0]((Resp = 0.000 | Mort = 0.000))            0.5
232            ((lds > 0.000) U[0,0] (n_edrk > 0.000))            0.5
231                ((af = 0.000) U[0,0] (dfa = 0.000))            0.5
230       F[0,0]((ICU_Pt_Days > 0.000 & Mort = 0.000))            0.5
631            ((LOS > 0.000) U[0,0] (n_edrk > 0.000))            0.5

[632 rows x 2 columns]

## Calculate Quality of Each Rule in Ruleset
First get misclassification rate of each individual rule ...

In [6]:
clientMCR = RQ.getRulesetMCR(clientRules, clientData, clientLabels)
clientMCR

,Rule,TP,TN,FP,FN,Actual Yes,Actual No,Predicted Yes,Predicted No,TPR/Sens,TNR/Spec,FPR,Precision,F1,Accuracy,MCR,BalancedAccuracy,Class
0,"G[0,0]((hr <= 0.000 & n_evts <= 0.000))",750,0,126,0,750,126,876,0,1.0,0.0,1.0,0.856164,0.922509,0.856164,0.143836,0.5,Negative
1,"F[0,0]((n_evts <= 0.000 -> O2_Flow >= 0.000))",750,0,126,0,750,126,876,0,1.0,0.0,1.0,0.856164,0.922509,0.856164,0.143836,0.5,Positive
2,"((lds >= 0.000) U[0,0] (n_evts >= 0.000))",750,0,126,0,750,126,876,0,1.0,0.0,1.0,0.856164,0.922509,0.856164,0.143836,0.5,Positive
3,"G[0,0]((O2_Flow <= 0.000 & y <= 0.000))",750,0,126,0,750,126,876,0,1.0,0.0,1.0,0.856164,0.922509,0.856164,0.143836,0.5,Negative
4,"F[0,0]((edrk <= 0.000 & n_evts >= 0.000))",750,0,126,0,750,126,876,0,1.0,0.0,1.0,0.856164,0.922509,0.856164,0.143836,0.5,Negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,"((lds <= 0.000) U[0,0] (Pulse >= 0.000))",750,0,126,0,750,126,876,0,1.0,0.0,1.0,0.856164,0.922509,0.856164,0.143836,0.5,Positive
612,"G[0,0]((GLUCOSE <= 0.000 -> Temp <= 0.000))",750,0,126,0,750,126,876,0,1.0,0.0,1.0,0.856164,0.922509,0.856164,0.143836,0.5,Positive
613,"((death >= 0.000) U[0,0] (Pulse >= 0.000))",750,0,126,0,750,126,876,0,1.0,0.0,1.0,0.856164,0.922509,0.856164,0.143836,0.5,Positive
614,"G[0,0]((death >= 0.000 -> PHOSPHORUS <= 0.000))",750,0,126,0,750,126,876,0,1.0,0.0,1.0,0.856164,0.922509,0.856164,0.143836,0.5,Negative
615,"G[0,0]((death >= 0.000 -> WHITE_BLOOD_CELL_COU...",750,0,126,0,750,126,876,0,1.0,0.0,1.0,0.856164,0.922509,0.856164,0.143836,0.5,Positive

In [7]:
ldpMCR = RQ.getRulesetMCR(ldpRules, clientData, clientLabels)
ldpMCR

,Rule,TP,TN,FP,FN,Actual Yes,Actual No,Predicted Yes,Predicted No,TPR/Sens,TNR/Spec,FPR,Precision,F1,Accuracy,MCR,BalancedAccuracy,Class
0,"G[0,0]((ICU_Pt_Days = 0.000 & n_evts < 0.000))",750,0,126,0,750,126,876,0,1.000000,0.000000,1.000000,0.856164,0.922509,0.856164,0.143836,0.500000,Negative
1,"((s8_edrk = 0.000) U[0,0] (s24_hr < 0.000))",397,85,41,353,750,126,438,438,0.529333,0.674603,0.325397,0.906393,0.668350,0.550228,0.449772,0.601968,Negative
2,"F[0,0]((death < 0.000 & ALBUMIN < 0.000))",750,0,126,0,750,126,876,0,1.000000,0.000000,1.000000,0.856164,0.922509,0.856164,0.143836,0.500000,Negative
3,"F[0,0]((n_evts = 0.000 & MAGNESIUM = 0.000))",750,0,126,0,750,126,876,0,1.000000,0.000000,1.000000,0.856164,0.922509,0.856164,0.143836,0.500000,Negative
4,"((Glasgow_Coma_Scale_Total < 0.000) U[0,0] (ld...",750,0,126,0,750,126,876,0,1.000000,0.000000,1.000000,0.856164,0.922509,0.856164,0.143836,0.500000,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627,"F[0,0]((direct = 0.000 & PHOSPHORUS = 0.000))",750,0,126,0,750,126,876,0,1.000000,0.000000,1.000000,0.856164,0.922509,0.856164,0.143836,0.500000,Negative
628,"F[0,0]((y > 0.000 & direct > 0.000))",750,63,63,0,750,126,813,63,1.000000,0.500000,0.500000,0.922509,0.959693,0.928082,0.071918,0.750000,Negative
629,"((MET > 0.000) U[0,0] (n_edrk < 0.000))",750,0,126,0,750,126,876,0,1.000000,0.000000,1.000000,0.856164,0.922509,0.856164,0.143836,0.500000,Negative
630,"((Glasgow_Coma_Scale_Total = 0.000) U[0,0] (ME...",750,18,108,0,750,126,858,18,1.000000,0.142857,0.857143,0.874126,0.932836,0.876712,0.123288,0.571429,Positive
631,"((LOS > 0.000) U[0,0] (n_edrk > 0.000))",749,18,108,1,750,126,857,19,0.998667,0.142857,0.857143,0.873979,0.932172,0.875571,0.124429,0.570762,Positive

## Calculate Entire Ruleset Quality

Majority voting methods are:  
AVG = multiply votes by weight, TOP = use top rules, MAJORITY is basic (count) majority vote

In [ ]:
#return confusion matrix summary across all patients

In [8]:
clientCM = RQ.getSummaryConfusionMatrix(clientData, clientLabels, clientMCR, method='AVG')
clientCM

,TP,TN,FP,FN,Actual Yes,Actual No,Predicted Yes,Predicted No,TPR/Sens,TNR/Spec,FPR,Precision,F1,Accuracy,MCR,BalancedAccuracy
0,750,0,126,0,750,126,876,0,1.0,0.0,1.0,0.856164,0.922509,0.856164,0.143836,0.5

In [9]:
ldpCM = RQ.getSummaryConfusionMatrix(clientData, clientLabels, ldpMCR, method='AVG')
ldpCM

,TP,TN,FP,FN,Actual Yes,Actual No,Predicted Yes,Predicted No,TPR/Sens,TNR/Spec,FPR,Precision,F1,Accuracy,MCR,BalancedAccuracy
0,750,0,126,0,750,126,876,0,1.0,0.0,1.0,0.856164,0.922509,0.856164,0.143836,0.5

In [10]:
#return confusion matrix patient by patient

In [ ]:
clientPtCM = RQ.getPatientConfusionMatrix(clientData, clientLabels, clientMCR, method='AVG')
clientPtCM

In [ ]:
ldpPtCM = RQ.getPatientConfusionMatrix(clientData, clientLabels, ldpMCR, method='AVG')
ldpPtCM